version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp-headless
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./wp/html:/var/www/html
      - ./wp/html/wp-content:/var/www/html/wp-content
  db:
    image: mysql:5.7
    container_name: wp-db
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./wp/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

  astro:
    build: ./astro
    container_name: astro
    ports:
      - "4321:4321"
    volumes:
      - ./astro:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
